
project_id = "plxuyxacefgttimodrbp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions.analyze-document-openai]
verify_jwt = true

[functions.analyze-document]
verify_jwt = true

