ALTER TABLE public.estate_notes
  ADD COLUMN IF NOT EXISTS priority TEXT,
  ADD COLUMN IF NOT EXISTS reminder_text TEXT,
  ADD COLUMN IF NOT EXISTS reminder_done BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS reminder_from TEXT,
  ADD COLUMN IF NOT EXISTS reminder_to TEXT,
  ADD COLUMN IF NOT EXISTS note_code TEXT,
  ADD COLUMN IF NOT EXISTS staff TEXT;